version: '2'
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./misc:/root/tahoe-lafs/misc
      - ./integration:/root/tahoe-lafs/integration
      - ./src:/root/tahoe-lafs/static
      - ./setup.cfg:/root/tahoe-lafs/setup.cfg
      - ./setup.py:/root/tahoe-lafs/setup.py
    ports:
      - "127.0.0.1:3456:3456" # web
      - "127.0.0.1:3460:3460" # sftp, to use run `docker-compose exec client sh -c 'echo "user password URI:DIR2:..." > /root/.tahoe-client/private/accounts' && docker-compose restart client` first
    depends_on:
      - "introducer"
      - "server"
    command: ["run", "/root/.tahoe-client"]
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./misc:/root/tahoe-lafs/misc
      - ./integration:/root/tahoe-lafs/integration
      - ./src:/root/tahoe-lafs/static
      - ./setup.cfg:/root/tahoe-lafs/setup.cfg
      - ./setup.py:/root/tahoe-lafs/setup.py
    ports:
      - "127.0.0.1:3457:3457" # tub
      - "127.0.0.1:3459:3459" # web
    depends_on:
      - "introducer"
    command: ["run", "/root/.tahoe-server"]
  introducer:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./misc:/root/tahoe-lafs/misc
      - ./integration:/root/tahoe-lafs/integration
      - ./src:/root/tahoe-lafs/static
      - ./setup.cfg:/root/tahoe-lafs/setup.cfg
      - ./setup.py:/root/tahoe-lafs/setup.py
    ports:
      - "127.0.0.1:3458:3458"
    command: ["run", "/root/.tahoe-introducer"]
